//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется NGEuser.rc
//
#define IDD_NGE_GUI                     102
#define IDR_MAINFRAME                   128
#define IDD_PROCESSING                  130
#define IDD_CAMERA                      132
#define IDD_MAIN                        134
#define IDD_LIGHTING                    135
#define IDD_FPGA                        136
#define IDD_MICROCONTROL                137
#define IDD_HANDSET                     138
#define IDD_ENHANCEMENT                 139
#define IDB_SANESO_PNG                  153
#define IDB_BITMAP_UP                   155
#define IDB_BITMAP_DOWN                 156
#define IDB_BITMAP_DOWN_PRESSED         157
#define IDB_BITMAP_UP_PRESSED           158
#define IDB_HANDSET_DIAGRAM             159
#define IDD_SYSTEM_MANAGER              160
#define IDD_SELF_CALIBRATION            161
#define IDB_SANESO_SPLASH               162
#define IDD_SELECT_ITEM                 164
#define IDD_PASSWORD                    165
#define IDD_SIGNALOUTPUT                166
#define IDD_SCREEN_SELECT               167
#define IDD_CEF_BROWSER                 168
#define IDC_ARM_CAMERAS                 1003
#define IDC_DISARM_CAMERAS              1004
#define IDC_COMBO_CAM_SELECT            1004
#define IDC_BUTTON_DUMP_CAM_SETTINGS    1005
#define IDC_RUN_FROM_IMAGES             1005
#define IDC_EDIT_CAM_GAIN               1006
#define IDC_SAVE_REPORT                 1006
#define IDC_EDIT_CAM_EXPOSURE           1007
#define IDC_CAM_IMAGE                   1008
#define IDC_BUTTON_CAM_LIVE             1009
#define IDC_BUTTON_CAM_UPDATE           1010
#define IDC_RADIO_LIVE_TRIGGERED        1011
#define IDC_RADIO_LIVE_FREERUN          1012
#define IDC_GROUP_LIVE                  1013
#define IDC_INSPECTION_MSG              1014
#define IDC_EDIT_PIXEL_SIZE             1014
#define IDC_BUTTON_UPDATE               1015
#define IDC_EDIT_CAM_SETTINGS_OVERRIDE  1015
#define IDC_BUTTON_CAM_CHOOSE_PFS       1016
#define IDC_EDIT_STAGE_VELOCITY         1017
#define IDC_EDIT_FRAME_DELAY            1018
#define IDC_BUTTON_RUN2                 1018
#define IDC_BUTTON_LIVE                 1018
#define IDC_BUTTON_LIVE_STREAM          1018
#define IDC_EDIT_NUM_FRAME_SETS         1019
#define IDC_BUTTON_PLAYBACK             1019
#define IDC_LIST_CAPTURE_POSITIONS      1020
#define IDC_BUTTON_RECORD               1020
#define IDC_INSPECTION_VIEW             1021
#define IDC_EDIT_PACKAGE_END            1021
#define IDC_BUTTON_TEXTURE2             1021
#define IDC_EDIT_NUM_CAMERAS            1022
#define IDC_BUTTON_RECORD2              1022
#define IDC_EDIT_IMAGE_FOLDER           1023
#define IDC_COMBO_STREAM_NAMES          1024
#define IDC_EDIT_FRAME_DELAY2           1025
#define IDC_EDIT_PACKAGE_WIDTH          1025
#define IDC_LIST1                       1026
#define IDC_LIST_LIVE_STREAM            1026
#define IDC_EDIT_PACKAGE_START          1026
#define IDC_LIST_COM_PORTS              1026
#define IDC_ITEM_LIST                   1026
#define IDC_BUTTON_LOAD                 1027
#define IDC_BUTTON_LOAD2                1028
#define IDC_BUTTON_SAVE                 1028
#define IDC_BUTTON_ALGO_EDIT            1028
#define IDC_CHECK1                      1029
#define IDC_CHECK_ENABLE_ALGOS          1029
#define IDC_CHECK_INVER_TRIGGER         1029
#define IDC_CHECK_BLEND_IMAGES          1029
#define IDC_CHECK_FILTER_FRAMES         1029
#define IDC_CHECK_TEST_PATTERN          1029
#define IDC_CHECK_SHADOW_FRONT_1        1029
#define IDC_CHECK_LOG_DEBUG             1029
#define IDC_CHECK_USE_STAGE_TRIGGERS    1030
#define IDC_CHECK_INVER_TRIGGER2        1030
#define IDC_CHECK_CLOSED_LOOP_STROBING  1030
#define IDC_CHECK_AUTO_EXPOSURE         1030
#define IDC_CHECK2                      1030
#define IDC_CHECK_SHADOW_LEFT_1         1030
#define IDC_BUTTON_LOAD_CAPTURE         1030
#define IDC_CHECK3                      1031
#define IDC_CHECK_SHADOW_RIGHT_1        1031
#define IDC_BUTTON_LOAD4                1031
#define IDC_BUTTON_DO_CAPTURE           1031
#define IDC_CHECK_AUTO_GAIN             1031
#define IDC_CHECK4                      1032
#define IDC_CHECK_SHADOW_TOP_1          1032
#define IDC_CHECK5                      1033
#define IDC_CHECK_SHADOW_BOTTOM_1       1033
#define IDC_CHECK6                      1034
#define IDC_CHECK_SHADOW_FRONT_2        1034
#define IDC_CHECK7                      1035
#define IDC_CHECK_SHADOW_LEFT_2         1035
#define IDC_EDIT_SAMPLE_ID              1036
#define IDC_CHECK8                      1036
#define IDC_CHECK_SHADOW_RIGHT_2        1036
#define IDC_CHECK9                      1037
#define IDC_CHECK_SHADOW_TOP_2          1037
#define IDC_CHECK10                     1038
#define IDC_CHECK_SHADOW_BOTTOM_2       1038
#define IDC_LED_MOSAIC                  1038
#define IDC_LED_FRONT_CAM               1039
#define IDC_RADIO_LONG_EDGE             1040
#define IDC_LED_TOP_CAM                 1040
#define IDC_RADIO_SHORT_EDGE            1041
#define IDC_LED_BOTTOM_CAM              1041
#define IDC_LED_LEFT_CAM                1042
#define IDC_LED_RIGHT_CAM               1043
#define IDC_LED_RIGHT_CAM2              1044
#define IDC_LED_CONTROLLER              1044
#define IDC_SELECT_FRONT_CAM            1045
#define IDC_SELECT_TOP_CAM              1046
#define IDC_LOCATION_TOP                1047
#define IDC_SELECT_BOTTOM_CAM           1047
#define IDC_LOCATION_BOTTOM             1048
#define IDC_SELECT_LEFT_CAM             1048
#define IDC_RADIO3                      1049
#define IDC_LOCATION_AUTO               1049
#define IDC_SELECT_RIGHT_CAM            1049
#define IDC_SELECT_ALL_CAM              1050
#define IDC_EDIT_MOSAIC_WIDTH           1051
#define IDC_EDIT_MOSAIC_HEIGHT          1052
#define IDC_EDIT_FPS_MOSAIC             1053
#define IDC_EDIT_FPS_FRONT_CAMERA       1054
#define IDC_EDIT_FPS_TOP_CAMERA         1055
#define IDC_EDIT_RED_GAIN               1055
#define IDC_EDIT_FPS_BOTTOM_CAMERA      1056
#define IDC_EDIT_GREEN_GAIN             1056
#define IDC_EDIT_FPS_LEFT_CAMERA        1057
#define IDC_EDIT_BLUE_GAIN              1057
#define IDC_EDIT_FPS_RIGHT_CAMERA       1058
#define IDC_BUTTON_WHITE_CAL            1058
#define IDC_MOSAIC_IMAGE                1059
#define IDC_EDIT_BAYER_TYPE             1059
#define IDC_EDIT_HEART_BEAT             1059
#define IDC_EDIT_VERSION                1060
#define IDC_BUTTON_SAVE_SETTINGS        1060
#define IDC_EDIT_EXPOSURE_TIME          1060
#define IDC_BUTTON_SAVE_NEXT_TRANSFER   1061
#define IDC_EDIT_VERSION2               1061
#define IDC_EDIT_STATUS                 1061
#define IDC_EDIT_GAIN                   1061
#define IDC_FPGA_CAMERA_LBL             1062
#define IDC_BUTTON_WHITE_CAL2           1062
#define IDC_BUTTON_FPN_CAL              1062
#define IDC_BUTTON_SAVE_NEXT_TRANSFER2  1062
#define IDC_BUTTON_SAVE_DEBUG_IMAGES    1062
#define IDC_EDIT_EEPROM_BOX             1062
#define IDC_EDIT_STATUS2                1062
#define IDC_EDIT_TRIGGER_STRING         1062
#define IDC_EDIT_DTR_OUTPUT_DURATION    1062
#define IDC_EDIT_EEPROM_SCOPE           1063
#define IDC_EDIT_GAMMA                  1063
#define IDC_LOGO                        1064
#define IDC_EDIT_CAMERA_SAT             1064
#define IDC_EDIT_LED_MUX_PERIOD         1064
#define IDC_LED_FRONT_COLOR1            1065
#define IDC_EDIT_CAMERA_AVG             1065
#define IDC_LED_FRONT_COLOR2            1066
#define IDC_EDIT_REGISTER               1066
#define IDC_EDIT_REGISTER_ADDRESS       1066
#define IDC_LED_FRONT_COLOR3            1067
#define IDC_EDIT_REGISTER_VAL           1067
#define IDC_LED_FRONT_COLOR4            1068
#define IDC_BUTTON_REGISTER_WRITE       1068
#define IDC_LED_FRONT_COLOR5            1069
#define IDC_BUTTON_REGISTER_READ        1069
#define IDC_LED_FRONT_COLOR6            1070
#define IDC_LED_FRONT_COLOR7            1071
#define IDC_LED_FRONT_COLOR8            1072
#define IDC_LED_FRONT_UP                1073
#define IDC_LED_FRONT_DOWN              1074
#define IDC_LED_FRONT_ON_OFF            1075
#define IDC_LED_FRONT_AUTO              1076
#define IDC_LED_SIDE_UP                 1077
#define IDC_LED_SIDE_DOWN               1078
#define IDC_LED_SIDE_ON_OFF             1079
#define IDC_LED_SIDE_AUTO               1080
#define IDC_LED_SIDE_LEVEL              1081
#define IDC_LED_FRONT_LEVEL             1082
#define IDC_LED_SIDE_ON_OFF2            1083
#define IDC_SHADOW_CAST_ON_OFF          1083
#define IDC_SLIDER1                     1084
#define IDC_SLIDER_FRONT_1              1084
#define IDC_ENHANCE_SHARPNESS_ON_OFF    1084
#define IDC_SLIDER_FRONT                1084
#define IDC_SLIDER2                     1085
#define IDC_SLIDER_SHADOW_CAST_DELAY    1085
#define IDC_TEMPORAL_AVERAGING_ON_OFF   1085
#define IDC_SLIDER3                     1086
#define IDC_SLIDER_FRONT_2              1086
#define IDC_SLIDER_ENHANCE_SHARPNESS    1086
#define IDC_LED_SIDE_ON_OFF3            1086
#define IDC_AUTO_SAT_OR_AVG             1086
#define IDC_SLIDER4                     1087
#define IDC_SLIDER_LEFT_1               1087
#define IDC_SLIDER_TEMPORAL_AVERAGING   1087
#define IDC_SLIDER_LEFT                 1087
#define IDC_SLIDER5                     1088
#define IDC_SLIDER_LEFT_2               1088
#define IDC_SPATIAL_AVERAGING_ON_OFF    1088
#define IDC_AUTO_MODE                   1088
#define IDC_SLIDER6                     1089
#define IDC_SLIDER_BOTTOM_1             1089
#define IDC_SLIDER_SPATIAL_AVERAGING    1089
#define IDC_SLIDER_BOTTOM               1089
#define IDC_SLIDER7                     1090
#define IDC_SLIDER_BOTTOM_2             1090
#define IDC_ENHANCE_GAMMA_ON_OFF        1090
#define IDC_SLIDER8                     1091
#define IDC_LED_SIDE_COLOR1             1091
#define IDC_SLIDER_ENHANCE_GAMMA        1091
#define IDC_LED_SIDE_COLOR2             1092
#define IDC_ENHANCE_BRIGHTNESS_ON_OFF   1092
#define IDC_SLIDER10                    1093
#define IDC_SLIDER_RIGHT_1              1093
#define IDC_SLIDER_ENHANCE_GAMMA2       1093
#define IDC_SLIDER_ENHANCE_BRIGHTNESS   1093
#define IDC_SLIDER_RIGHT                1093
#define IDC_SLIDER11                    1094
#define IDC_SLIDER_RIGHT_2              1094
#define IDC_ENHANCE_GAMMA_SIDE_ON_OFF   1094
#define IDC_SLIDER_AUTO_SETPOINT        1094
#define IDC_SLIDER12                    1095
#define IDC_SLIDER_TOP_1                1095
#define IDC_SLIDER_ENHANCE_SIDE_GAMMA   1095
#define IDC_SLIDER_ENHANCE_GAMMA_SIDE   1095
#define IDC_SLIDER_TOP                  1095
#define IDC_SLIDER13                    1096
#define IDC_SLIDER_TOP_2                1096
#define IDC_SLIDER_AUTO_GAINP           1096
#define IDC_SCALING_ON_OFF              1096
#define IDC_DIAGRAM                     1097
#define IDC_LED_SIDE_COLOR3             1097
#define IDC_SLIDER_SCALE_SLOPE          1097
#define IDC_SWITCH1                     1098
#define IDC_LED_SIDE_COLOR4             1098
#define IDC_SLIDER_SCALE_OFFSET         1098
#define IDC_SWITCH2                     1099
#define IDC_LED_SIDE_COLOR5             1099
#define IDC_FRONT_SCALING_ON_OFF        1099
#define IDC_SWITCH3                     1100
#define IDC_LED_SIDE_COLOR6             1100
#define IDC_FRONT_SLIDER_SCALE          1100
#define IDC_SLIDER_FRONT_SCALE_SLOPE    1100
#define IDC_SWITCH4                     1101
#define IDC_LED_SIDE_COLOR7             1101
#define IDC_COMBO_SWITCH1               1102
#define IDC_LED_SIDE_COLOR8             1102
#define IDC_COMBO_SWITCH2               1103
#define IDC_SLIDER_AUTO_GAINI           1103
#define IDC_BUTTON_SELECT_BAND_IMAGING  1103
#define IDC_COMBO_SWITCH3               1104
#define IDC_BUTTON_DEMO_FEATURES        1104
#define IDC_ENHANCE_PRESET1             1104
#define IDC_COMBO_SWITCH4               1105
#define IDC_BUTTON_EDIT_SETTINGS        1105
#define IDC_ENHANCE_PRESET2             1105
#define IDC_SLIDER_AUTO_GAIND           1105
#define IDC_ENHANCE_PRESET3             1106
#define IDC_SWITCH5                     1106
#define IDC_ENHANCE_PRESET4             1107
#define IDC_COMBO_SWITCH5               1107
#define IDC_ENHANCE_PRESET5             1108
#define IDC_ENHANCE_PRESET6             1109
#define IDC_ENHANCE_PRESET7             1110
#define IDC_ENHANCE_PRESET8             1111
#define IDC_ENHANCE_CONTRAST_ON_OFF     1112
#define IDC_SLIDER_ENHANCE_CONTRAST     1113
#define IDC_BUTTON1                     1114
#define IDC_BUTTON_RESET                1114
#define IDC_BUTTON_EEPROM_BOX_READ      1114
#define IDC_BUTTON_TEMPORAL_AVERAGING_TYPE 1114
#define IDC_BUTTON_START_SELF_CAL       1114
#define IDC_BUTTON_OPERATOR             1114
#define IDI_GREEN_LED_ICON              1115
#define IDC_BUTTON_CALIBRATE2           1115
#define IDC_BUTTON_EEPROM_BOX_WRITE     1115
#define IDC_BUTTON_SPATIAL_AVERAGING_TYPE 1115
#define IDC_BUTTON_CAL_WHITE            1115
#define IDC_BUTTON_PROCESSING           1115
#define IDI_GRAY_LED_ICON               1116
#define IDC_BUTTON__RESET_MICROCONTROLLER 1116
#define IDC_BUTTON_EEPROM_SCOPE_READ    1116
#define IDC_BUTTON_RESET_MICROCONTROLLER 1116
#define IDC_ENHANCE_ALL_OFF             1116
#define IDC_BUTTON_LIGHTING             1116
#define IDI_RED_LED_ICON                1117
#define IDC_BUTTON_SAVE_RAW             1117
#define IDC_BUTTON_SAVE_RAW_IMAGE       1117
#define IDC_BUTTON_INITIALIZE           1117
#define IDC_BUTTON_EEPROM_SCOPE_WRITE   1117
#define IDC_BUTTON_CAL_FPN              1117
#define IDC_BUTTON_HANDSET              1117
#define IDI_YELLOW_LED_ICON             1118
#define IDC_BUTTON_RESET_USB_CHIPS      1118
#define IDC_BUTTON_EEPROM_BOX_READ_FILE 1118
#define IDC_BUTTON_ENHANCEMENT          1118
#define IDI_BLUE_LED_ICON               1119
#define IDC_BUTTON_EEPROM_BOX_WRITE_FILE 1119
#define IDC_BUTTON_360_SYSTEM_CALIBRATION 1119
#define IDC_BUTTON_CONNECT              1120
#define IDC_BUTTON_SYSTEM_MANAGER       1120
#define IDC_BUTTON_EEPROM_SCOPE_READ_FILE 1121
#define IDC_BUTTON_SEND_NOW             1121
#define IDC_BUTTON_CAMERA               1121
#define IDC_EDIT1                       1122
#define IDC_ITEM_EDIT                   1122
#define IDC_BUTTON_EEPROM_SCOPE_WRITE_FILE 1122
#define IDC_EDIT_LAST_CAL               1122
#define IDC_ED                          1122
#define IDC_EDIT_SW_VERSION             1122
#define IDC_EDIT_PASSWORD               1122
#define IDC_BUTTON_MICRO_CONTROLLER     1122
#define IDC_BUTTON_WRITE_TO_SCOPE       1123
#define IDC_BUTTON_REFLASH              1123
#define IDC_BUTTON_SIGNAL_OUTPUT        1123
#define IDC_LED_LAST_CAL                1124
#define IDC_LED_CAL_CAMERAS_OK          1125
#define IDC_LED_CAL_CUP_CHECK           1126
#define IDC_RADIO_SIGNAL_ON             1126
#define IDC_RADIO_BREAK_SET             1126
#define IDC_LED_CAL_LIGHTS_OK           1127
#define IDC_RADIO_SIGNAL_ON2            1127
#define IDC_RADIO_SIGNAL_OFF            1127
#define IDC_FRONT_USB_VERSION           1127
#define IDC_RADIO_BREAK_CLEAR           1127
#define IDC_LED_CAL_FPN                 1128
#define IDC_RADIO_DTR_SET               1128
#define IDC_LED_CAL_WB                  1129
#define IDC_TOP_USB_VERSION             1129
#define IDC_RADIO_DTR_CLEAR             1129
#define IDC_LED_CAL_OVERALL             1130
#define IDC_BOTTOM_USB_VERSION          1130
#define IDC_RADIO_RTS_SET               1130
#define IDC_LEFT_USB_VERSION            1131
#define IDC_RADIO_RTS_CLEAR             1131
#define IDC_FRONT_USB_VERSION5          1132
#define IDC_RIGHT_USB_VERSION           1132
#define IDC_BUTTON_DEFAULT_SETTINGS     1133
#define IDC_RADIO_UPSAMPLE1             1134
#define IDC_RADIO_UPSAMPLE2             1135
#define IDC_RADIO_UPSAMPLE3             1136

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1135
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
